### ISSUE TITLE
Travis CI

### ISSUE THREAD

**Issue by corporateshark** [corporateshark/WalCommander#303]
https://travis-ci.org/corporateshark/WalCommander/builds/48038113

```
Using worker: worker-linux-de84ae74-1.bb.travis-ci.org:travis-linux-20
system_info
Build system information
Build language: cpp
Build image provisioning date and time
Sat Dec 13 04:56:50 UTC 2014
lsb_release -a
Distributor ID:	Ubuntu
Description:	Ubuntu 12.04 LTS
Release:	12.04
Codename:	precise
Cookbooks Version
4f2272c https://github.com/travis-ci/travis-cookbooks/tree/4f2272c
GCC version
gcc (Ubuntu/Linaro 4.6.3-1ubuntu5) 4.6.3
Copyright (C) 2011 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
LLVM version
clang version 3.4 (tags/RELEASE_34/final)
Target: x86_64-unknown-linux-gnu
Thread model: posix
Pre-installed Ruby versions
ruby-1.9.3-p551
Pre-installed Node.js versions
v0.10.33
Pre-installed Go versions
go1.4
Redis version
redis-server 2.8.18
riak version
1.4.12
MongoDB version
MongoDB 2.4.12
CouchDB version
couchdb 1.6.1
Neo4j version
1.9.4
Cassandra version
2.0.9
RabbitMQ Version
3.4.2
ElasticSearch version
1.4.0
Installed Sphinx versions
2.0.10
2.1.9
2.2.4
Default Sphinx version
2.1.9
Installed Firefox version
firefox 31.0esr
PhantomJS version
1.9.8
ant -version
Apache Ant(TM) version 1.8.2 compiled on December 3 2011
mvn -version
Apache Maven 3.2.3 (33f8c3e1027c3ddde99d3cdebad2656a31e8fdf4; 2014-08-11T20:58:10+00:00)
Maven home: /usr/local/maven
Java version: 1.7.0_72, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-7-oracle/jre
Default locale: en, platform encoding: UTF-8
OS name: "linux", version: "2.6.32-042stab090.5", arch: "amd64", family: "unix"
git.checkout
0.75s$ git clone --depth=50 --branch=master git://github.com/corporateshark/WalCommander.git corporateshark/WalCommander
Cloning into 'corporateshark/WalCommander'...
remote: Counting objects: 1011, done.
remote: Compressing objects: 100% (656/656), done.
remote: Total 1011 (delta 598), reused 613 (delta 340)
Receiving objects: 100% (1011/1011), 4.58 MiB | 0 bytes/s, done.
Resolving deltas: 100% (598/598), done.
Checking connectivity... done.
$ cd corporateshark/WalCommander
$ git checkout -qf 8e31c3f169429fc89ad0d870d07e7e9ffeadf125
Setting environment variables from .travis.yml
$ export BUILDMODE=custom
$ export CXX=g++
$ export CC=gcc
$ gcc --version
gcc (Ubuntu/Linaro 4.6.3-1ubuntu5) 4.6.3
Copyright (C) 2011 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
before_script.1
1.16s$ sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test
Executing: gpg --ignore-time-conflict --no-options --no-default-keyring --secret-keyring /tmp/tmp.EJG8ipOLWI --trustdb-name /etc/apt/trustdb.gpg --keyring /etc/apt/trusted.gpg --primary-keyring /etc/apt/trusted.gpg --keyring /etc/apt/trusted.gpg.d//apt.postgresql.org.gpg --keyserver hkp://keyserver.ubuntu.com:80/ --recv 60C317803A41BA51845E371A1E9377A2BA9EF27F
gpg: requesting key BA9EF27F from hkp server keyserver.ubuntu.com
gpg: key BA9EF27F: public key "Launchpad Toolchain builds" imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
before_script.2
0.84s$ sudo add-apt-repository --yes ppa:tobydox/mingw
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/dist-packages/softwareproperties/ppa.py", line 95, in run
    self.add_ppa_signing_key(self.ppa_path)
  File "/usr/lib/python2.7/dist-packages/softwareproperties/ppa.py", line 105, in add_ppa_signing_key
    ppa_info = get_ppa_info_from_lp(owner_name, ppa_name)
  File "/usr/lib/python2.7/dist-packages/softwareproperties/ppa.py", line 83, in get_ppa_info_from_lp
    return json.loads(lp_page)
  File "/usr/lib/python2.7/json/__init__.py", line 326, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
3.38s$ sudo apt-get -qq update
W: Failed to fetch http://ppa.launchpad.net/tobydox/mingw/ubuntu/dists/precise/main/source/Sources  404  Not Found
W: Failed to fetch http://ppa.launchpad.net/tobydox/mingw/ubuntu/dists/precise/main/binary-amd64/Packages  404  Not Found
W: Failed to fetch http://ppa.launchpad.net/tobydox/mingw/ubuntu/dists/precise/main/binary-i386/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.
The command "sudo apt-get -qq update" failed and exited with 100 during .
Your build has been stopped.
```

**Comment by AMDmi3** [comment]
See #304
